version: "3"

services:
  app:
    container_name: app
    restart: always
    build: ./app
    ports:
      - "5000:5000"
    command: gunicorn -w 4 -b 0.0.0.0:5000 wsgi:server

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
